spring.application.name=ventureflow-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/venture_flow
spring.datasource.username=postgres
spring.datasource.password=3488

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true